---
- name: Zero Networks Management
  ignore_unreachable: true
  hosts: all
  environment:
    LC_CTYPE: en_US.utf8

  tasks:
  - name: dynamic
    shell: "{{command}}"
    register: results
  - debug:
        var: results.stdout
